=== 13steinj/MKVToolNix/examples/matroskachapters.dtd
<!ELEMENT Chapters (EditionEntry*)>
<!ELEMENT EditionEntry (ChapterAtom*)>

<!ELEMENT ChapterAtom (
          ChapterTimeStart,
          ChapterTimeEnd?,
          ChapterTrack?,
          ChapterDisplay+,
          ChapterAtom*)>

<!ELEMENT ChapterTrack (ChapterTrackNumber)>
<!ELEMENT ChapterDisplay (
          ChapterString,
          ChapterLanguage+,
          ChapterCountry*)>

<!ELEMENT ChapterTimeStart (#PCDATA)>
<!ELEMENT ChapterTimeEnd (#PCDATA)>

<!ELEMENT ChapterString (#PCDATA)>
<!ELEMENT ChapterLanguage (#PCDATA)>
<!ELEMENT ChapterCountry (#PCDATA)>

=== 13steinj/MKVToolNix/doc/example-chapters-1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE Chapters SYSTEM "matroskachapters.dtd">

<!-- $Id$ -->

<!-- A simple example. The movie in question contains four parts: -->
<!-- The intro starting at the beginning, the first act, the second -->
<!-- act, and the credits. -->

<!-- Note that the end timestamps are optional. -->

<!-- The timestamps use the normal format of HH:MM:SS.mmm with -->
<!-- HH beging the hour, MM the minute, SS the second and -->
<!-- mmm the milliseconds. -->

<Chapters>
  <EditionEntry>
    <ChapterAtom>
      <ChapterTimeStart>00:00:00.000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Intro</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterTimeStart>00:01:00.000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Act 1</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterTimeStart>00:05:30.000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Act 2</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterTimeStart>00:12:20.000</ChapterTimeStart>
      <ChapterTimeEnd>00:12:55.000</ChapterTimeEnd>
      <ChapterDisplay>
        <ChapterString>Credits</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
    </ChapterAtom>
  </EditionEntry>
</Chapters>
